#include "bsp_fir_f32.h"

// I-type FIR Filter coefficients generated by MATLAB Filter Designer v25.2
// Parameters: Lowpass, Equiripple, order = 48, wpass = 0.05, wstop = 0.2
static const float32_t pCoefs[FIR_PAIRS + 1] = {
	 5.296254e-05,  6.479785e-04,  1.095185e-03,  1.766477e-03,
	 2.384799e-03,  2.723875e-03,  2.495939e-03,  1.429159e-03,
	-6.477179e-04, -3.713141e-03, -7.477983e-03, -1.134918e-02,
	-1.445399e-02, -1.573347e-02, -1.409869e-02, -8.630202e-03,
	 1.214409e-03,  1.542761e-02,  3.335224e-02,  5.368706e-02,
	 7.460805e-02,  9.399204e-02,  1.097141e-01,  1.199625e-01,
	 1.235215e-01,
};

void BSP_FIR_f32(const float32_t *pSrc, float32_t *pDst)
{
	for (uint32_t i = 0; i < FIR_DST_SIZE; ++i)
	{
		const float32_t *ps1 = pSrc + i;
		const float32_t *ps2 = pSrc + i + FIR_TAP_SIZE - 1;
		float32_t sum = pCoefs[FIR_PAIRS] * pSrc[i + FIR_PAIRS];
		for (uint32_t j = 0; j < FIR_PAIRS; ++j)
			sum += pCoefs[j] * (*ps1++ + *ps2--);
		pDst[i] = sum;
	}
}
