#include "bsp_fir_f32.h"

// I-type FIR Filter coefficients generated by MATLAB Filter Designer v25.2
// Parameters: Lowpass, Equiripple, order = 48, wpass = 0.2, wstop = 0.5
static const float32_t pCoefs[FIR_TAP_SIZE] = {
	 5.296254e-05,  6.479785e-04,  1.095185e-03,  1.766477e-03,
	 2.384799e-03,  2.723875e-03,  2.495939e-03,  1.429159e-03,
	-6.477179e-04, -3.713141e-03, -7.477983e-03, -1.134918e-02,
	-1.445399e-02, -1.573347e-02, -1.409869e-02, -8.630202e-03,
	 1.214409e-03,  1.542761e-02,  3.335224e-02,  5.368706e-02,
	 7.460805e-02,  9.399204e-02,  1.097141e-01,  1.199625e-01,
	 1.235215e-01,  1.199625e-01,  1.097141e-01,  9.399204e-02,
	 7.460805e-02,  5.368706e-02,  3.335224e-02,  1.542761e-02,
	 1.214409e-03, -8.630202e-03, -1.409869e-02, -1.573347e-02,
	-1.445399e-02, -1.134918e-02, -7.477983e-03, -3.713141e-03,
	-6.477179e-04,  1.429159e-03,  2.495939e-03,  2.723875e-03,
	 2.384799e-03,  1.766477e-03,  1.095185e-03,  6.479785e-04,
	 5.296254e-05,
};

static float32_t pState[FIR_SRC_SIZE + FIR_TAP_SIZE - 1];

void BSP_FIR_f32(const float32_t *pSrc, float32_t *pDst)
{
	arm_fir_instance_f32 S;
	arm_fir_init_f32(&S, FIR_TAP_SIZE, pCoefs, pState, FIR_SRC_SIZE);
	arm_fir_f32(&S, pSrc, pDst, FIR_SRC_SIZE);
}
